name: ${project.name}
main: net.daboross.bukkitdev.displaynamemessages.DisplayNameMessagesPlugin
version: ${project.version}
author: Dabo Ross
description: Changes username to display name on join, quit, and death events
